<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>${project.packageName}</groupId>
        <artifactId>${service.name?replace(" ","-")?lower_case}</artifactId>
        <version>${project.version!'0.0.1-SNAPSHOT'}</version>
    </parent>
    <artifactId>${module.name?lower_case?replace("[^a-z0-9]","",'r')}</artifactId>
    <name>${module.name}</name>
    <properties>
        <java.version>21</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>io.mateu</groupId>
            <artifactId>annotation-processor-mvc</artifactId>
            <version>0.0.1-MATEU</version>
        </dependency>
        <dependency>
            <groupId>io.mateu</groupId>
            <artifactId>mvc-core</artifactId>
            <version>0.0.1-MATEU</version>
        </dependency>
        <dependency>
            <groupId>io.mateu</groupId>
            <artifactId>vaadin-lit</artifactId>
            <version>0.0.1-MATEU</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </path>
                        <path>
                            <groupId>io.mateu</groupId>
                            <artifactId>annotation-processor-mvc</artifactId>
                            <version>0.0.1-MATEU</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
