package e2e;

import org.junit.jupiter.api.Test;

/**
 * User-journey e2e of the generated apps (GENERATED by modux — regenerate with
 * the model). Requires the system up (../up.sh). Each test drives the app as a
 * user: form login, menu navigation, use-case forms filled with sample values,
 * CRUD listings.
 */
public class AppsE2eTest extends BaseE2eTest {
<#list apps as app>

    // ── ${app.title} (:${app.port?c}) ─────────────────────────────────────────
    @Test
    void ${app.name}LoginYHome() {
        var page = newPage();
        loginAndOpen(page, "http://localhost:${app.port?c}${app.path}", "${app.username}", "${app.password}");
        waitVisible(page, "text=${app.title}");
        page.close();
    }
<#list app.useCasePages as uc>

    @Test
    void ${app.name}Pagina${uc.methodName?cap_first}() {
        var page = newPage();
        loginAndOpen(page, "http://localhost:${app.port?c}${app.path}", "${app.username}", "${app.password}");
        openMenuEntry(page, "${uc.menuLabel}");
<#if uc.fields?has_content>
<#list uc.fields as f>
<#if f.type != "bool">
        page.getByLabel("${f.label}", new com.microsoft.playwright.Page.GetByLabelOptions().setExact(true)).first().fill("${f.sample?j_string}");
<#if f.type == "date" || f.type == "datetime" || f.type == "time">
        // Enter commits the typed date AND closes the picker overlay (Escape would
        // revert the value, and an open overlay covers the submit button)
        page.keyboard().press("Enter");
</#if>
</#if>
</#list>
</#if>
        page.locator("vaadin-button:has-text(\"${uc.buttonLabel}\"), button:has-text(\"${uc.buttonLabel}\")").first().click();
        // The flow only succeeded when its success message shows. A backend failure
        // (an exception in the use case — e.g. an unimplemented custom step) surfaces
        // as an error instead, and this wait turns the test RED: the journey is broken,
        // not just «the page did not render».
        page.waitForSelector("text=${uc.successMessage?j_string}",
                new com.microsoft.playwright.Page.WaitForSelectorOptions().setTimeout(20000));
        page.close();
    }
</#list>
<#list app.crudLabels as label>

    @Test
    void ${app.name}Listado${label?replace("[^A-Za-z0-9áéíóúñÁÉÍÓÚÑ ]","")?replace(" ", "")?cap_first}() {
        var page = newPage();
        loginAndOpen(page, "http://localhost:${app.port?c}${app.path}", "${app.username}", "${app.password}");
        openMenuEntry(page, "${label}");
        waitVisible(page, "input[placeholder='Search'], vaadin-grid, [role='grid'], table");
        page.close();
    }
</#list>
</#list>
<#list shells![] as sh>

    // The shell's OIDC flow: unauthenticated visitors land on keycloak (provisioned by
    // up.sh with the 'shell' client; admin/admin is the dev default) and come back to
    // the secured home with its remote menus.
    @Test
    void shell${sh.slug?cap_first}LoginOidc() {
        var page = newPage();
        page.navigate("http://localhost:8100/");
        page.waitForTimeout(5000);
        if (page.url().contains(":8080/")) {
            page.locator("input[name='username'], #username").first().fill("admin");
            page.locator("input[name='password'], #password").first().fill("admin");
            page.locator("button[type='submit'], input[type='submit'], #kc-login").first().click();
            page.waitForTimeout(5000);
        }
        waitVisible(page, "text=${sh.title}");
        page.close();
    }
</#list>
}
