package e2e;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * User-journey e2e of the generated apps (GENERATED by modux — regenerate with
 * the model). Requires the system up (../up.sh). Each test drives the app as a
 * user: form login, menu navigation, use-case forms filled with sample values,
 * CRUD listings.
 */
public class AppsE2eTest extends BaseE2eTest {
<#list apps as app>

    // ── ${app.title} (:${app.port?c}) ─────────────────────────────────────────
    @Test
    void ${app.name}LoginYHome() {
        var page = newPage();
        loginAndOpen(page, "http://localhost:${app.port?c}${app.path}", "${app.username}", "${app.password}");
        waitVisible(page, "text=${app.title}");
        page.close();
    }
<#list app.useCasePages as uc>

    @Test
    void ${app.name}Pagina${uc.methodName?cap_first}() {
        var page = newPage();
        loginAndOpen(page, "http://localhost:${app.port?c}${app.path}", "${app.username}", "${app.password}");
        openMenuEntry(page, "${uc.menuLabel}");
<#if uc.fields?has_content>
<#list uc.fields as f>
<#if f.sample == "texto-e2e" || f.sample == "e2e@example.com" || f.sample == "https://example.com">
        page.getByLabel("${f.label}", new com.microsoft.playwright.Page.GetByLabelOptions().setExact(true)).first().fill("${f.sample}");
</#if>
</#list>
</#if>
        page.locator("vaadin-button:has-text(\"${uc.buttonLabel}\"), button:has-text(\"${uc.buttonLabel}\")").first().click();
        page.waitForLoadState();
        page.waitForTimeout(1000);
        assertTrue((Boolean) page.locator("body").evaluate("e => e.textContent.length > 0"),
                "la página '${uc.menuLabel}' (${app.name}) no responde tras enviar");
        page.close();
    }
</#list>
<#list app.crudLabels as label>

    @Test
    void ${app.name}Listado${label?replace("[^A-Za-z0-9áéíóúñÁÉÍÓÚÑ ]","")?replace(" ", "")?cap_first}() {
        var page = newPage();
        loginAndOpen(page, "http://localhost:${app.port?c}${app.path}", "${app.username}", "${app.password}");
        openMenuEntry(page, "${label}");
        waitVisible(page, "input[placeholder='Search'], vaadin-grid, [role='grid'], table");
        page.close();
    }
</#list>
</#list>
<#list shells![] as sh>

    // The shell's OIDC flow: unauthenticated visitors land on keycloak (provisioned by
    // up.sh with the 'shell' client; admin/admin is the dev default) and come back to
    // the secured home with its remote menus.
    @Test
    void shell${sh.slug?cap_first}LoginOidc() {
        var page = newPage();
        page.navigate("http://localhost:8100/");
        page.waitForTimeout(5000);
        if (page.url().contains(":8080/")) {
            page.locator("input[name='username'], #username").first().fill("admin");
            page.locator("input[name='password'], #password").first().fill("admin");
            page.locator("button[type='submit'], input[type='submit'], #kc-login").first().click();
            page.waitForTimeout(5000);
        }
        waitVisible(page, "text=${sh.title}");
        page.close();
    }
</#list>
}
