-- V${version} migration generated by Modux from model changes.
-- Additive changes (new tables and columns) are applied automatically. Destructive or ambiguous
-- changes are listed at the bottom as comments — review and apply them by hand.
<#if newTables?has_content>

-- New tables
<#list newTables as table>
<#if table.sequence??>
CREATE SEQUENCE IF NOT EXISTS ${table.sequence} START WITH 1 INCREMENT BY 1;
</#if>
CREATE TABLE IF NOT EXISTS ${table.name} (
<#list table.columns as col>
    ${col.name} ${col.type}<#if col.pk> PRIMARY KEY</#if><#sep>,</#sep>
</#list>
);
</#list>
</#if>
<#if addedColumns?has_content>

-- New columns
<#list addedColumns as col>
ALTER TABLE ${col.table} ADD COLUMN IF NOT EXISTS ${col.name} ${col.type};
</#list>
</#if>
<#if review?has_content>

-- ⚠ Destructive / ambiguous changes — NOT applied automatically. Review against live data first:
<#list review as line>
-- ${line}
</#list>
</#if>
