-- Baseline schema generated by Modux from the model.
-- This is the V1 migration: it is applied once and is immutable. Later model changes
-- produce new V{n} migrations (a hand-edited applied migration breaks Flyway's checksum).
<#list tables as table>

<#if table.sequence??>
CREATE SEQUENCE IF NOT EXISTS ${table.sequence} START WITH 1 INCREMENT BY 1;
</#if>
CREATE TABLE IF NOT EXISTS ${table.name} (
<#list table.columns as col>
    ${col.name} ${col.type}<#if col.pk> PRIMARY KEY</#if><#sep>,</#sep>
</#list>
);
</#list>
