{
  "name": "${page.name}",
  "description": "Generated by Modux from page ${page.name}",
  "fields": [
<#list pageModel.fields as f>
    {
      "id": "${f.id!f.name}",
      "label": "${f.name}",
      "dataType": "${f.type!'string'}"
    }<#sep>,
</#list>
  ]
}
