{
  <#-- a deterministic id, so a workflow's USER_TASK can point at this form: the schema requires
       formId on a human step, and an auto-generated one would be different on every import -->
  "id": "form-${page.name?lower_case?replace("[^a-z0-9]+","-",'r')?replace("(^-+|-+$)","",'r')}",
  "name": "${page.name}",
  "description": "Generated by Modux from page ${page.name}",
  "fields": [
<#list pageModel.fields as f>
    {
      "id": "${f.id!f.name}",
      "label": "${f.name}",
      "dataType": "${f.type!'string'}"
    }<#sep>,
</#list>
  ]
}
