# Terraform skeleton for ${project.name}
# Provider: ${project.terraformProvider!'(unset)'}   Backend: ${project.terraformBackendType!'local'}
#
# This is a starting point generated by Modux. Fill in credentials, networking and the
# resources each service needs (database, message broker, container runtime).

terraform {
  required_version = ">= 1.5.0"
<#if project.terraformBackendType?? && project.terraformBackendType?has_content && project.terraformBackendType?lower_case != "local">
  backend "${project.terraformBackendType?lower_case}" {
    # configure remote state here
  }
</#if>
}

<#if project.terraformProvider?? && project.terraformProvider?has_content>
provider "${project.terraformProvider?lower_case}" {
  # configure region / credentials here
}
</#if>

# Services that make up the ${project.name} system:
<#list project.services as svc>
# - ${svc.name} (port ${(svc.port!8080)?c})
</#list>
