# Terraform skeleton for ${project.name}
# Provider: ${project.terraformProvider!'(unset)'}   Backend: ${project.terraformBackendType!'local'}
#
# This is a starting point generated by Modux. Fill in credentials, networking and the
# resources each service needs (database, message broker, container runtime).

<#assign hetzner = (project.terraformProvider!'') == 'Hetzner'>
terraform {
  required_version = ">= 1.5.0"
<#if hetzner>
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = "~> 1.45"
    }
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.0"
    }
  }
</#if>
<#if project.terraformBackendType?? && project.terraformBackendType?has_content && project.terraformBackendType?lower_case != "local">
  backend "${project.terraformBackendType?lower_case}" {
    # configure remote state here
  }
</#if>
}

<#if hetzner>
# Hetzner Cloud: the infrastructure AROUND the Cloudfleet-managed cluster (the cluster
# itself lives in Cloudfleet; nodes/volumes/load balancers can be managed from here).
variable "hcloud_token" {
  description = "Hetzner Cloud API token"
  type        = string
  sensitive   = true
}

provider "hcloud" {
  token = var.hcloud_token
}
<#if dnsRecords?? && dnsRecords?has_content>

# DNS on Cloudflare: one record per URL declared on the distribution map, pointing
# at the cluster's ingress IP.
variable "cloudflare_api_token" {
  description = "Cloudflare API token (Zone.DNS edit)"
  type        = string
  sensitive   = true
}

variable "cloudflare_zone_id" {
  description = "Cloudflare zone the records belong to"
  type        = string
}

variable "ingress_ip" {
  description = "Public IP of the cluster ingress the URLs resolve to"
  type        = string
}

provider "cloudflare" {
  api_token = var.cloudflare_api_token
}
<#list dnsRecords as host>

resource "cloudflare_record" "${host?replace("[^a-zA-Z0-9]", "_", 'r')}" {
  zone_id = var.cloudflare_zone_id
  name    = "${host}"
  type    = "A"
  content = var.ingress_ip
  proxied = true
}
</#list>
</#if>
<#elseif project.terraformProvider?? && project.terraformProvider?has_content>
provider "${project.terraformProvider?lower_case}" {
  # configure region / credentials here
}
</#if>

# Services that make up the ${project.name} system:
<#list project.services as svc>
# - ${svc.name} (port ${(svc.port!8080)?c})
</#list>
