<#assign wfTopic = project.name?lower_case?replace("[^a-z0-9]","-",'r') + ".workflow." + saga.name?lower_case?replace("[^a-z0-9]","-",'r')>
{
  "name": "${saga.name}",
  "version": ${(saga.version!0)?c},
  "description": "Generated by Modux from saga ${saga.name}",
  "status": "DRAFT",
<#if (saga.defaultMaxStepExecutions!0) gt 0>
  "defaultMaxStepExecutions": ${saga.defaultMaxStepExecutions?c},
</#if>
  "steps": [
<#list saga.steps as step>
    {
      "id": "${step.id}",
      "type": "ACTION",
      "name": "${step.name}",
      "topic": "${wfTopic}.${step.id?lower_case?replace("[^a-z0-9]","-",'r')}",
      "retries": ${(saga.maxRetries!0)?c}<#if step?index gt 0>,
      "preconditionStepId": "${saga.steps[step?index-1].id}"</#if><#if (saga.timeoutMs!0) gt 0>,
      "timeout": ${saga.timeoutMs?c}</#if><#if step.compensatingStepId??>,
      "rollbackable": true,
      "compensationStepId": "${step.compensatingStepId}"</#if><#if (step.maxSuccessfulExecutions!0) gt 0>,
      "maxSuccessfulExecutions": ${step.maxSuccessfulExecutions?c}</#if>
    }<#sep>,
<#else>
    {
      "id": "done",
      "type": "END",
      "name": "Done"
    }
</#list>
  ]
}
