package io.mateu.modux.modeldrivengenerator.application.usecases.project.aicomplete;

import io.mateu.modux.modeldrivengenerator.infra.out.ai.ClaudeApiClient;
import io.mateu.modux.modeldrivengenerator.infra.out.persistence.file.*;
import io.mateu.uidl.data.FieldDataType;
import lombok.RequiredArgsConstructor;
import lombok.SneakyThrows;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Slf4j
public class AiCompleteCodeUseCase {

    final CommonFileRepository repository;
    final ClaudeApiClient claude;

    private static final String BASE_SYSTEM = """
            You are an expert Java 21 developer implementing Domain-Driven Design patterns with Spring Boot.
            Respond with only the requested Java code — no markdown fences, no explanation, no preamble.
            The code will be inserted directly into a method body or a file.
            """;

    @SneakyThrows
    public void handle(AiCompleteCodeCommand command) {
        var project = repository.findById(command.projectId(), ProjectEntity.class).orElseThrow();
        var outputPath = command.outputPath() != null && !command.outputPath().isBlank()
                ? command.outputPath()
                : project.outputPath();

        for (var serviceId : project.serviceIds()) {
            var service = repository.findById(serviceId, ServiceEntity.class).orElseThrow();
            for (var moduleId : service.moduleIds()) {
                var module = repository.findById(moduleId, ModuleEntity.class).orElseThrow();
                processModule(command, project, service, module, outputPath);
            }
        }
    }

    @SneakyThrows
    private void processModule(AiCompleteCodeCommand command,
                               ProjectEntity project, ServiceEntity service,
                               ModuleEntity module, String outputPath) {
        var slug = moduleSlug(module.name());
        var proposals = new ArrayList<String>();

        proposals.add("# AI Code Proposals — " + module.name() + " module\n");
        proposals.add("> Generated by `mvn modux:ai-complete`. Review every proposal before committing.\n");

        for (var aggregateId : safeList(module.aggregateIds())) {
            var aggregate = repository.findById(aggregateId, AggregateEntity.class).orElseThrow();
            processAggregate(command, project, module, aggregate, proposals);
        }

        processBddSteps(command, module, proposals);

        var proposalDir = Path.of(outputPath, "proposals", slug);
        Files.createDirectories(proposalDir);
        Files.writeString(proposalDir.resolve("AI-PROPOSALS.md"),
                String.join("\n", proposals));
        log.info("AI proposals written to {}", proposalDir.resolve("AI-PROPOSALS.md").toAbsolutePath());
    }

    private void processAggregate(AiCompleteCodeCommand command,
                                   ProjectEntity project, ModuleEntity module,
                                   AggregateEntity aggregate,
                                   List<String> proposals) {
        var fields = resolveFields(aggregate);

        // ── Invariants ──────────────────────────────────────────────────────────
        if (aggregate.invariants() != null && !aggregate.invariants().isEmpty()) {
            proposals.add("\n## " + aggregate.name() + " — `checkInvariants()`\n");

            var invariantDesc = aggregate.invariants().stream()
                    .map(inv -> formatInvariant(inv))
                    .collect(Collectors.joining("\n"));

            String system = BASE_SYSTEM + extraContext(module);
            String user = """
                    Aggregate: %s
                    Fields:
                    %s

                    Implement the body of the `checkInvariants()` method.
                    Invariants to enforce:
                    %s

                    Rules:
                    - Throw IllegalArgumentException with the error message when an invariant is violated
                    - Use null-safe checks where appropriate
                    - Return only the statements that go inside the method body (no signature, no braces)
                    """.formatted(aggregate.name(), fields, invariantDesc);

            var code = claude.complete(command.apiKey(), command.model(), system, user);
            proposals.add("```java\n" + code.strip() + "\n```\n");
            proposals.add("*File: `domain/aggregates/" + aggregate.name().toLowerCase()
                    + "/" + aggregate.name() + ".java` → `checkInvariants()`*\n");
        }

        // ── Operation preconditions ──────────────────────────────────────────────
        if (aggregate.operations() != null) {
            for (var op : aggregate.operations()) {
                if (op.preconditions() == null || op.preconditions().isBlank()) continue;
                proposals.add("\n## " + aggregate.name() + " — `check"
                        + capitalize(op.name()) + "Preconditions()`\n");

                String system = BASE_SYSTEM + extraContext(module);
                String user = """
                        Aggregate: %s
                        Fields:
                        %s

                        Implement the body of the `check%sPreconditions()` method.
                        Preconditions (plain text description): %s

                        Rules:
                        - Throw IllegalArgumentException or a domain exception when a precondition is not met
                        - Return only the statements inside the method body (no signature, no braces)
                        """.formatted(aggregate.name(), fields, capitalize(op.name()), op.preconditions());

                var code = claude.complete(command.apiKey(), command.model(), system, user);
                proposals.add("```java\n" + code.strip() + "\n```\n");
                proposals.add("*File: `domain/aggregates/" + aggregate.name().toLowerCase()
                        + "/" + aggregate.name() + ".java` → `check" + capitalize(op.name())
                        + "Preconditions()`*\n");
            }
        }
    }

    private void processBddSteps(AiCompleteCodeCommand command,
                                  ModuleEntity module,
                                  List<String> proposals) {
        var scenariosFromModule = safeList(module.bddScenarios());
        // Also look up global bddScenarios that reference this module's aggregates
        var globalScenarios = repository.findAllOfType(BddScenarioEntity.class);

        if (scenariosFromModule.isEmpty() && globalScenarios.isEmpty()) return;

        var allScenarios = new ArrayList<BddScenarioEntity>(scenariosFromModule);
        globalScenarios.stream()
                .filter(s -> !allScenarios.contains(s))
                .forEach(allScenarios::add);

        if (allScenarios.isEmpty()) return;

        proposals.add("\n## BDD Step implementations\n");

        // Build field context from all aggregates in this module
        var aggregateContext = safeList(module.aggregateIds()).stream()
                .map(id -> repository.findById(id, AggregateEntity.class).orElseThrow())
                .map(agg -> "Aggregate " + agg.name() + ":\n" + resolveFields(agg))
                .collect(Collectors.joining("\n\n"));

        for (var scenario : allScenarios) {
            if (scenario.steps() == null || scenario.steps().isBlank()) continue;
            proposals.add("\n### Scenario: " + scenario.name() + "\n");

            String system = BASE_SYSTEM + extraContext(module);
            String user = """
                    You are implementing Cucumber step definitions for a Spring Boot application.

                    Domain context:
                    %s

                    BDD Scenario:
                    Feature: %s
                    Scenario: %s
                    Steps:
                    %s

                    For each step that needs a Java implementation, provide the method body.
                    Format your response as:
                    STEP: <exact step text>
                    CODE:
                    <java statements>
                    END

                    Repeat for each step that needs implementation.
                    Use @Autowired repository beans to set up or verify state.
                    Use realistic test data values.
                    """.formatted(aggregateContext,
                    scenario.feature() != null ? scenario.feature() : "Feature",
                    scenario.name(),
                    scenario.steps());

            var code = claude.complete(command.apiKey(), command.model(), system, user);
            proposals.add("```\n" + code.strip() + "\n```\n");
        }
    }

    // ── Helpers ─────────────────────────────────────────────────────────────────

    private String resolveFields(AggregateEntity aggregate) {
        if (aggregate.modelId() == null || aggregate.modelId().isBlank()) return "(no fields defined)";
        var model = repository.findById(aggregate.modelId(), ModelEntity.class).orElse(null);
        if (model == null || model.fields() == null) return "(no fields defined)";
        return model.fields().stream()
                .map(f -> "  - " + javaType(f) + " " + f.name())
                .collect(Collectors.joining("\n"));
    }

    /**
     * Maps a ModelFieldEntity to a Java type string.
     *
     * ModelFieldEntity fields:
     *   - basicType (boolean): true = primitive wrapper (the Java type comes from f.type() FieldDataType)
     *   - type (FieldDataType): the data type; for basicType=true this gives the primitive kind
     *   - modelId (String): for basicType=false, ID of the referenced model/value-object/entity
     *
     * When basicType=true  → field.type() holds the primitive FieldDataType (string, integer, date, …)
     * When basicType=false → field is either a ValueObject or an Entity reference
     */
    private String javaType(ModelFieldEntity f) {
        if (f.basicType()) {
            return primitiveJavaType(f.type());
        }
        // Non-basic: could be ValueObject or Entity — use capitalized field name as the type
        // (matches aggregate.ftl which uses ${field.name?cap_first} for ValueObject fields)
        return capitalize(f.name());
    }

    private String primitiveJavaType(FieldDataType type) {
        if (type == null) return "String";
        return switch (type) {
            case string -> "String";
            case integer -> "Integer";
            case number -> "java.math.BigDecimal";
            case bool -> "Boolean";
            case date -> "java.time.LocalDate";
            case time -> "java.time.LocalTime";
            case dateTime -> "java.time.LocalDateTime";
            case file -> "String";
            case money -> "java.math.BigDecimal";
            default -> "String";
        };
    }

    private String formatInvariant(InvariantEntity inv) {
        var sb = new StringBuilder("- Name: \"" + inv.name() + "\"");
        if (inv.conditions() != null) {
            for (var c : inv.conditions()) {
                if (c.expression() != null && !c.expression().isBlank())
                    sb.append(", Expression hint: \"").append(c.expression()).append("\"");
                if (c.errorMessage() != null && !c.errorMessage().isBlank())
                    sb.append(", Error message: \"").append(c.errorMessage()).append("\"");
            }
        }
        return sb.toString();
    }

    private String extraContext(ModuleEntity module) {
        if (module.llmSystemPrompt() != null && !module.llmSystemPrompt().isBlank())
            return "\nAdditional context for this module:\n" + module.llmSystemPrompt() + "\n";
        return "";
    }

    private String moduleSlug(String name) {
        return name.toLowerCase().replaceAll("[^a-z0-9]", "");
    }

    private String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    private <T> List<T> safeList(List<T> list) {
        return list != null ? list : List.of();
    }
}
