apiVersion: v1
kind: Secret
metadata:
  name: {{ include "modux.fullname" . }}-db
type: Opaque
stringData:
  MODUX_DB_USER: {{ include "modux.dbUser" . | quote }}
  MODUX_DB_PASSWORD: {{ include "modux.dbPassword" . | quote }}
