package io.mateu.modux.modeldrivengenerator.application.usecases.workflow;

import io.mateu.modux.modeldrivengenerator.infra.out.persistence.file.WorkflowEntity;
import io.mateu.modux.modeldrivengenerator.infra.out.persistence.file.WorkflowGatewayEntity;
import io.mateu.modux.modeldrivengenerator.infra.out.persistence.file.WorkflowStepEntity;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;

/**
 * A modux workflow, as the EventConductor definition that runs it.
 *
 * <p>Pure model→model: no repository, no files, so the whole translation is unit-testable and the
 * generated JSON can be validated against EventConductor's own schema.
 *
 * <p>Two shapes differ between the two sides and this is where they meet:
 *
 * <ul>
 *   <li><b>A gateway is a STEP.</b> modux models a join or a split as its own element, because on
 *       a canvas it is its own box. EventConductor has no such thing — a JOIN and a FORK are steps
 *       like any other. So the gateways fold into the step list here.</li>
 *   <li><b>Dependencies are preconditions.</b> modux says «this step depends on those»;
 *       EventConductor says «these must have completed first». Same edge, read from the same end,
 *       so {@code dependsOnStepIds} becomes {@code preconditionStepIds} verbatim.</li>
 * </ul>
 */
public final class EventConductorWorkflowDefinition {

    private EventConductorWorkflowDefinition() {}

    /**
     * The definition for {@code workflow}.
     *
     * @param gateways the gateways that belong to this workflow — they become steps
     * @param formIdOf the form id for a page, for the human steps ({@code null} when it has none)
     * @param topicPrefix what an ACTION step's topic is namespaced under
     */
    public static Map<String, Object> of(WorkflowEntity workflow,
                                         List<WorkflowGatewayEntity> gateways,
                                         Function<String, String> formIdOf,
                                         String topicPrefix) {
        var definition = new LinkedHashMap<String, Object>();
        definition.put("name", workflow.name());
        definition.put("description", workflow.description() != null
                ? workflow.description()
                : "Generated by Modux from workflow " + workflow.name());
        definition.put("status", "DRAFT");
        if (workflow.defaultMaxStepExecutions() != null) {
            definition.put("defaultMaxStepExecutions", workflow.defaultMaxStepExecutions());
        }

        var steps = new ArrayList<Map<String, Object>>();
        for (var step : workflow.steps() == null ? List.<WorkflowStepEntity>of() : workflow.steps()) {
            steps.add(step(step, formIdOf, topicPrefix));
        }
        for (var gateway : gateways) {
            steps.add(gateway(gateway));
        }
        // a definition with no steps is rejected by the schema; an END is the honest empty workflow
        if (steps.isEmpty()) {
            steps.add(new LinkedHashMap<>(Map.of("id", "done", "type", "END", "name", "Done")));
        }
        definition.put("steps", steps);
        return definition;
    }

    private static Map<String, Object> step(WorkflowStepEntity step,
                                            Function<String, String> formIdOf,
                                            String topicPrefix) {
        var type = step.type() != null ? step.type() : "ACTION";
        var out = new LinkedHashMap<String, Object>();
        out.put("id", step.id());
        out.put("type", type);
        out.put("name", step.name() != null ? step.name() : step.id());
        if (step.description() != null) out.put("description", step.description());

        // an ACTION is dispatched to a topic; the schema requires one
        if ("ACTION".equals(type)) {
            out.put("topic", topicPrefix + "." + slug(step.id()));
        }
        // a USER_TASK is rendered as a form; the schema requires one
        if ("USER_TASK".equals(type) && step.formPageId() != null) {
            var formId = formIdOf.apply(step.formPageId());
            if (formId != null) out.put("formId", formId);
        }
        var dependencies = step.dependsOnStepIds();
        if (dependencies != null && !dependencies.isEmpty()) {
            out.put("preconditionStepIds", List.copyOf(dependencies));
        }
        if (step.compensationUseCaseId() != null) {
            out.put("rollbackable", true);
            out.put("compensationStepId", step.compensationUseCaseId());
        }
        if (step.maxSuccessfulExecutions() != null) {
            out.put("maxSuccessfulExecutions", step.maxSuccessfulExecutions());
        }
        return out;
    }

    /**
     * A gateway as a step. modux's own vocabulary survives here on purpose: a gateway is a
     * canvas element with {@code type} SPLIT/JOIN and {@code semantics} PARALLEL/EXCLUSIVE or
     * ALL/ANY, and this is the one place that turns it into EventConductor's FORK/JOIN + joinType.
     */
    private static Map<String, Object> gateway(WorkflowGatewayEntity gateway) {
        var join = !"SPLIT".equals(gateway.type());
        var out = new LinkedHashMap<String, Object>();
        out.put("id", gateway.id());
        out.put("type", join ? "JOIN" : "FORK");
        out.put("name", gateway.name() != null ? gateway.name() : gateway.id());
        if (join) {
            // ALL waits for every branch (AND); ANY proceeds with the first (XOR)
            out.put("joinType", "ANY".equals(gateway.semantics()) ? "XOR" : "AND");
        }
        var sources = gateway.sourceIds();
        if (sources != null && !sources.isEmpty()) {
            out.put("preconditionStepIds", List.copyOf(sources));
        }
        return out;
    }

    /** What the workflow's ACTION topics are namespaced under. */
    public static String topicPrefix(String projectName, String workflowName) {
        return slug(projectName) + ".workflow." + slug(workflowName);
    }

    /** The deterministic id of the form generated from a page — what a USER_TASK points at. */
    public static String formId(String pageName) {
        return "form-" + slug(pageName);
    }

    private static String slug(String value) {
        return value == null ? "" : value.toLowerCase().replaceAll("[^a-z0-9]+", "-")
                .replaceAll("(^-+|-+$)", "");
    }
}
